#!/usr/bin/env bash
#
# Set up the local Zigbee coordinator stack (Mosquitto + Zigbee2MQTT) on the
# board.  Run it ON the Orange Pi, not on the workstation.
#
#   ssh orangepi@192.168.0.234
#   cd smart_home_AI && ./scripts/install-zigbee2mqtt.sh
#
# It is safe to re-run: existing credentials are kept rather than regenerated,
# because rotating them silently would lock Zigbee2MQTT out of the broker.
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ZIGBEE_DIR="${PROJECT_ROOT}/deploy/zigbee"
MOSQUITTO_DIR="${ZIGBEE_DIR}/mosquitto"
Z2M_DIR="${ZIGBEE_DIR}/zigbee2mqtt"
ENV_FILE="${PROJECT_ROOT}/.env"
COMPOSE_FILE="${PROJECT_ROOT}/docker-compose.zigbee.yml"

PASSWD_FILE="${MOSQUITTO_DIR}/passwd"
SECRET_FILE="${Z2M_DIR}/secret.yaml"

MQTT_USER="zigbee2mqtt"

info()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
warn()  { printf '  ! %s\n' "$*" >&2; }
die()   { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- preflight

[[ -f "${COMPOSE_FILE}" ]] || die "Run this from a checkout that has docker-compose.zigbee.yml."
command -v docker >/dev/null || die "docker is not installed. See scripts/install-home-assistant-docker.sh."
docker compose version >/dev/null 2>&1 || die "The docker compose plugin is missing."

if ! docker ps >/dev/null 2>&1; then
  die "Cannot talk to the Docker daemon as $(id -un). Try 'newgrp docker' or log out and back in."
fi

# ------------------------------------------------------------ find adapter

info "Looking for the Zigbee adapter"

# The by-id path is the only stable one.  /dev/ttyUSB0 moves when USB devices
# enumerate in a different order, which this board does - it already carries two
# Bluetooth controllers.
mapfile -t CANDIDATES < <(ls /dev/serial/by-id/* 2>/dev/null || true)

ADAPTER="${ZIGBEE_ADAPTER:-}"

if [[ -n "${ADAPTER}" ]]; then
  echo "  using ZIGBEE_ADAPTER from the environment"
elif [[ ${#CANDIDATES[@]} -eq 0 ]]; then
  die "No serial adapters found under /dev/serial/by-id/.

Plug the Sonoff ZBDongle-P in (through the USB extension cable, not directly
into the board) and run this again. To see what the kernel made of it:

    dmesg | tail -20"
elif [[ ${#CANDIDATES[@]} -eq 1 ]]; then
  ADAPTER="${CANDIDATES[0]}"
  echo "  found ${ADAPTER}"
else
  echo "  more than one serial device is present:"
  for index in "${!CANDIDATES[@]}"; do
    printf '    [%d] %s\n' "$((index + 1))" "${CANDIDATES[$index]}"
  done
  read -rp "  Which one is the Zigbee dongle? [1-${#CANDIDATES[@]}] " choice
  [[ "${choice}" =~ ^[0-9]+$ ]] || die "Not a number."
  (( choice >= 1 && choice <= ${#CANDIDATES[@]} )) || die "Out of range."
  ADAPTER="${CANDIDATES[$((choice - 1))]}"
fi

[[ -e "${ADAPTER}" ]] || die "${ADAPTER} does not exist."

if [[ ! -r "${ADAPTER}" || ! -w "${ADAPTER}" ]]; then
  warn "$(id -un) cannot read/write ${ADAPTER} yet."
  warn "You are in: $(id -Gn)"
  warn "The dialout group owns serial devices; add yourself and re-login if missing:"
  warn "    sudo usermod -aG dialout $(id -un)"
fi

# ------------------------------------------------------------- credentials

info "Preparing credentials"

mkdir -p "${MOSQUITTO_DIR}" "${Z2M_DIR}"

random_secret() {
  # tr can exit non-zero when head closes the pipe early; that is expected.
  LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c "${1:-32}" || true
}

if [[ -f "${SECRET_FILE}" ]]; then
  echo "  keeping existing ${SECRET_FILE#"${PROJECT_ROOT}/"}"
  MQTT_PASSWORD="$(awk '/^mqtt_password:/ {print $2}' "${SECRET_FILE}")"
  [[ -n "${MQTT_PASSWORD}" ]] || die "${SECRET_FILE} has no mqtt_password. Delete it and re-run."
else
  MQTT_PASSWORD="$(random_secret 32)"
  FRONTEND_TOKEN="$(random_secret 32)"
  [[ ${#MQTT_PASSWORD} -eq 32 && ${#FRONTEND_TOKEN} -eq 32 ]] || die "Could not generate secrets from /dev/urandom."

  cat > "${SECRET_FILE}" <<SECRETS
# Generated by scripts/install-zigbee2mqtt.sh. Not in git.
# Referenced from configuration.yaml as '!secret <name>'.
mqtt_user: ${MQTT_USER}
mqtt_password: ${MQTT_PASSWORD}
frontend_token: ${FRONTEND_TOKEN}
SECRETS
  chmod 600 "${SECRET_FILE}"
  echo "  wrote ${SECRET_FILE#"${PROJECT_ROOT}/"}"
fi

# Mosquitto refuses to load a world-writable password file, and runs as its own
# uid inside the container, so it must stay world-readable.
if [[ -f "${PASSWD_FILE}" && -r "${PASSWD_FILE}" ]] && grep -q "^${MQTT_USER}:" "${PASSWD_FILE}" 2>/dev/null; then
  echo "  keeping existing broker password file"
else
  # mosquitto_passwd runs as root inside the image.  Without --user the file
  # lands on the host owned by root at mode 0600, which breaks it twice over:
  # this script cannot chmod it, and the broker - uid 1883 inside its own
  # container - cannot read it either, so the stack would crash-loop instead of
  # failing here where the message is useful.
  #
  # Removing a stale one works whoever owns it: unlink needs write permission on
  # the directory, which we have, not ownership of the file.
  rm -f "${PASSWD_FILE}"
  docker run --rm -i \
    --user "$(id -u):$(id -g)" \
    -v "${MOSQUITTO_DIR}:/work" \
    eclipse-mosquitto:2 \
    mosquitto_passwd -c -b /work/passwd "${MQTT_USER}" "${MQTT_PASSWORD}" \
    || die "Could not generate the Mosquitto password file."
  # World-readable so the broker's uid can read it.  Mosquitto refuses a
  # world-WRITABLE password file, which 0644 is not.
  chmod 644 "${PASSWD_FILE}"
  echo "  wrote ${PASSWD_FILE#"${PROJECT_ROOT}/"}"
fi

# Assert the property the broker actually depends on, rather than trusting that
# the steps above produced it.
[[ -r "${PASSWD_FILE}" ]] || die "${PASSWD_FILE} is not readable by $(id -un).
Remove it with 'sudo rm ${PASSWD_FILE}' and run this again."

# ------------------------------------------------------------ live config

info "Preparing Zigbee2MQTT configuration"

# Same example/local split as configs/devices.example.yaml: Zigbee2MQTT rewrites
# configuration.yaml on first start with the generated network key and PAN IDs,
# so the live file is network identity and is git-ignored.  Never overwrite one
# that already exists - that would orphan every paired device.
if [[ -f "${Z2M_DIR}/configuration.yaml" ]]; then
  echo "  keeping existing configuration.yaml (network already formed)"
else
  cp "${Z2M_DIR}/configuration.example.yaml" "${Z2M_DIR}/configuration.yaml"
  echo "  seeded configuration.yaml from the example"
  echo "  channel 25 - change it now if you want a different one; after pairing,"
  echo "  changing the channel means re-pairing every device."
fi

# ----------------------------------------------------------------- env var

info "Recording the adapter path in .env"

touch "${ENV_FILE}"
if grep -q '^ZIGBEE_ADAPTER=' "${ENV_FILE}"; then
  # Rewrite in place rather than appending a second definition, which would
  # shadow confusingly depending on who reads the file.
  tmp="$(mktemp)"
  grep -v '^ZIGBEE_ADAPTER=' "${ENV_FILE}" > "${tmp}"
  printf 'ZIGBEE_ADAPTER=%s\n' "${ADAPTER}" >> "${tmp}"
  mv "${tmp}" "${ENV_FILE}"
  echo "  updated ZIGBEE_ADAPTER"
else
  printf '\n# Stable by-id path of the Zigbee coordinator. Set by install-zigbee2mqtt.sh.\nZIGBEE_ADAPTER=%s\n' "${ADAPTER}" >> "${ENV_FILE}"
  echo "  added ZIGBEE_ADAPTER"
fi

# ------------------------------------------------------------------- start

info "Starting the stack"

cd "${PROJECT_ROOT}"
docker compose -f "${COMPOSE_FILE}" up -d

echo
echo "  waiting for Zigbee2MQTT to open the adapter..."
for _ in $(seq 1 30); do
  if docker logs zigbee2mqtt 2>&1 | grep -qi 'Connected to MQTT server'; then
    echo "  broker connection established"
    break
  fi
  if docker logs zigbee2mqtt 2>&1 | grep -qiE 'Error while starting zigbee-herdsman|failed to connect'; then
    warn "Zigbee2MQTT reported a startup error. Full log:"
    warn "    docker logs zigbee2mqtt"
    break
  fi
  sleep 2
done

# ------------------------------------------------------------------- report

FRONTEND_TOKEN="$(awk '/^frontend_token:/ {print $2}' "${SECRET_FILE}")"
BOARD_IP="$(hostname -I | awk '{print $1}')"

info "Done"
cat <<REPORT
  Adapter        ${ADAPTER}
  Broker         mqtt://127.0.0.1:1883  (loopback only, user '${MQTT_USER}')
  Zigbee2MQTT UI http://${BOARD_IP}:8080
  UI token       ${FRONTEND_TOKEN}

Next, and only these two things are manual:

  1. Add MQTT to Home Assistant.
     Settings -> Devices & Services -> Add Integration -> MQTT
       Broker   127.0.0.1
       Port     1883
       Username ${MQTT_USER}
       Password  (see deploy/zigbee/zigbee2mqtt/secret.yaml)

     Paired sensors then appear in Home Assistant on their own, because
     configuration.yaml has homeassistant.enabled set.

  2. Pair a sensor.
     Open the UI above, click "Permit join", then wake the sensor - usually a
     long press on its reset button until the LED blinks. Pair the device
     nearest the coordinator first so the mesh grows outward.

Useful afterwards:

  docker logs -f zigbee2mqtt
  docker compose -f docker-compose.zigbee.yml restart zigbee2mqtt
  docker compose -f docker-compose.zigbee.yml down

Your Tuya sensors are standard Zigbee and should join here, but pairing them
to this coordinator removes them from the Tuya app and from the Tuya cloud
integration in Home Assistant. Their entity IDs will change - the Phase 1
automation rules reference them, so re-check the rules after re-pairing.
REPORT
